### ISSUE TITLE
Spent hours but couldn't get it to working... Help Needed...

### ISSUE THREAD

**Issue by timurcatakli** [AbelHeinsbroek/chartjs-plugin-crosshair#103]
Hello everyone,
I spent hours to get this plugin working but no luck. May someone please send me a link to a working version.

I am using the following versions:
`"chart.js": "^3.7.1",`
`"react-chartjs-2": "^4.1.0",`
`"chartjs-plugin-crosshair": "^1.2.0",`

My chart is a stacked chart...

<img width="868" alt="image" src="https://user-images.githubusercontent.com/15508978/169676388-55f1b40d-ae85-49ff-a7e8-ef9cd5d6df89.png">

Thanks a lot...

**Comment by jayantbh** [comment]
I'm not the maintainer of this repo, but as a general suggestion it would be great if you could show what you've tried, which code snippets did you use.

You've shared a screenshot and versions, which is great, but I can see you're using `react-chartjs-2`, which could make it possible that the issue is in that package instead, and as of now the maintainers don't know if you've contacted them/created an issue there about it since you've not linked any such issue.

**Comment by nategrift** [comment]
This issue is stale, please download latest version of the plugin and try again. If it still doesn't work please create a new issue and provide both code examples and more details.
